name: homelab

include:
  # Reverse Proxy
  - podman/traefik/compose.yml

  # Services with backup
  # - podman/restic/compose.yml
  - podman/vaultwarden/compose.yml
  - podman/icloud-photo/compose.yml
  - podman/gickup/compose.yml

  # Services without backup
  - podman/it-tools/compose.yml
  - podman/arcane/compose.yml
  - podman/glance/compose.yml
  # - podman/grafana/compose.yml
  # - podman/frigate/compose.yml
  - podman/adguard/compose.yml

  # Services for media
  - podman/qbittorrent/compose.yml
  - podman/oneonefive/compose.yml
  - podman/mkvtoolnix/compose.yml
  - podman/makemkv/compose.yml
