name: homelab

services:

  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    volumes:
      - ${UPTIME_KUMA_DATA}:/app/data
    ports:
      - ${UPTIME_KUMA_PORT}:3001
    extra_hosts:
      - host.ip:${HOST_IP}

  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ${VAULTWARDEN_DATA}:/data
    ports:
      - ${VAULTWARDEN_PORT}:80
    environment:
      - SIGNUPS_ALLOWED=false # Comment this line to allow signups

  icloud-photo:
    image: icloudpd/icloudpd:latest
    restart: unless-stopped
    volumes:
      - ${ICLOUD_PHOTO_DATA}:/data
    ports:
      - ${ICLOUD_PHOTO_PORT}:8080
    environment:
      - TZ=${TZ}
    command: icloudpd --directory /data --username ${ICLOUD_USERNAME} --password-provider webui --mfa-provider webui --watch-with-interval 3600