name: homelab

include:
  # Reverse Proxy
  - docker/traefik/compose.yml

  # Services with backup
  - docker/restic/compose.yml
  - docker/vaultwarden/compose.yml
  - docker/icloud-photo/compose.yml
  - docker/gickup/compose.yml

  # Services without backup
  - docker/it-tools/compose.yml
  - docker/arcane/compose.yml
  - docker/glance/compose.yml
  - docker/grafana/compose.yml
  - docker/frigate/compose.yml
  - docker/adguard/compose.yml

  # Services for media
  - docker/qbittorrent/compose.yml
  - docker/oneonefive/compose.yml
  - docker/mkvtoolnix/compose.yml
  - docker/makemkv/compose.yml

  # Testing services
  # - docker/testpod/compose.yml
