name: homelab

include:
  - path:
    - docker/uptime-kuma.yml
    - docker/vaultwarden.yml
    - docker/icloud-photo.yml
    - docker/restic.yml
    - docker/netdata.yml
    - docker/komodo.yml
    - docker/jenkins.yml
    - docker/it-tools.yml
    - docker/makemkv.yml
    - docker/mkvtoolnix.yml
    - docker/scrutiny.yml