services:

  makemkv:
    image: docker.io/jlesage/makemkv:v26.07.2
    container_name: homelab-makemkv
    restart: unless-stopped
    # devices: # Use lsblk to find the correct devices for the optical drive
    #   - ${MAKEMKV_DEVICE_SR}
    #   - ${MAKEMKV_DEVICE_SG}
    volumes:
      - ${FAST_TEMP_STORAGE}/makemkv:/config:rw,Z
      - ${MASS_TEMP_STORAGE}/shared:/storage:rw,z
      - ${MASS_TEMP_STORAGE}/shared:/output:rw,z
    environment:
      - USER_ID=0
      - GROUP_ID=0
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.makemkv.rule=Host(`makemkv.${DOMAIN_NAME}`)"
      - "traefik.http.routers.makemkv.entrypoints=websecure"
      - "traefik.http.services.makemkv.loadbalancer.server.port=5800"
