services:

  icloud-photo:
    image: icloudpd/icloudpd:latest
    restart: unless-stopped
    volumes:
      - ${ICLOUD_PHOTO_DATA}:/data
    ports:
      - ${ICLOUD_PHOTO_PORT}:8080
    environment:
      - TZ=${TZ}
    command: >-
      icloudpd
      --directory /data
      --username ${ICLOUD_USERNAME}
      --password-provider webui
      --mfa-provider webui
      --watch-with-interval 3600