services:

  makemkv:
    image: jlesage/makemkv
    restart: unless-stopped
    devices:
      - ${MAKEMKV_DEVICE_SR}
      - ${MAKEMKV_DEVICE_SG}
    volumes:
      - ${MAKEMKV_OUTPUT}:/output
      - makemkv_config:/config
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.makemkv-local.rule=Host(`makemkv.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.makemkv-local.entrypoints=websecure"
      - "traefik.http.routers.makemkv-local.tls.certresolver=cloudflare-local"
      - "traefik.http.routers.makemkv-local.tls.domains[0].main=local.${DOMAIN_NAME}"
      - "traefik.http.routers.makemkv-local.tls.domains[0].sans=*.local.${DOMAIN_NAME}"

      - "traefik.http.routers.makemkv-remote.rule=Host(`makemkv.remote.${DOMAIN_NAME}`)"
      - "traefik.http.routers.makemkv-remote.entrypoints=websecure"
      - "traefik.http.routers.makemkv-remote.tls.certresolver=cloudflare-remote"
      - "traefik.http.routers.makemkv-remote.tls.domains[0].main=remote.${DOMAIN_NAME}"
      - "traefik.http.routers.makemkv-remote.tls.domains[0].sans=*.remote.${DOMAIN_NAME}"

      - "traefik.http.services.makemkv.loadbalancer.server.port=5800"


volumes:
  makemkv_config: