services:

  restic-backup:
    image: mazzolino/restic:latest
    hostname: restic-backup
    restart: unless-stopped
    environment:
      RUN_ON_STARTUP: "true"
      BACKUP_CRON: "0 0 * * * *"
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_BACKUP_SOURCES: /mnt/source
      RESTIC_BACKUP_ARGS: >-
        --tag backup
        --exclude ._*
        --exclude .DS_Store
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-hourly 24
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      POST_COMMANDS_FAILURE: |-
        curl -X POST -d 'urls=${DISCORD_WEBHOOK}&body=Restic backup failed' http://apprise:8000/notify
      TZ: ${TZ}
    volumes:
      - ${RESTIC_SOURCE}:/mnt/source:ro

  restic-prune:
    image: mazzolino/restic:latest
    hostname: restic-prune
    restart: unless-stopped
    environment:
      SKIP_INIT: "true"
      RUN_ON_STARTUP: "false"
      PRUNE_CRON: "0 30 4 * * *"
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      TZ: ${TZ}

  restic-check:
    image: mazzolino/restic:latest
    hostname: restic-check
    restart: unless-stopped
    environment:
      SKIP_INIT: "true"
      RUN_ON_STARTUP: "false"
      CHECK_CRON: "0 45 4 * * 0"
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=500M
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      TZ: ${TZ}

  apprise:
    image: caronc/apprise:latest
