services:

  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    volumes:
      - /run/udev:/run/udev:ro
      - scrutiny_config:/opt/scrutiny/config
      - scrutiny_influxdb:/opt/scrutiny/influxdb
    devices:
      # Add more devices if you have more than 2 hard drives
      - ${SCRUTINY_DEVICE_01}
      - ${SCRUTINY_DEVICE_02}
    environment:
      - TZ=${TZ}
      - "COLLECTOR_CRON_SCHEDULE=30 4 * * *"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.scrutiny-local.rule=Host(`scrutiny.local.${DOMAIN_NAME}`)"
      - "traefik.http.routers.scrutiny-local.entrypoints=websecure"
      - "traefik.http.routers.scrutiny-local.tls.certresolver=cloudflare-local"
      - "traefik.http.routers.scrutiny-local.tls.domains[0].main=local.${DOMAIN_NAME}"
      - "traefik.http.routers.scrutiny-local.tls.domains[0].sans=*.local.${DOMAIN_NAME}"

      - "traefik.http.routers.scrutiny-remote.rule=Host(`scrutiny.remote.${DOMAIN_NAME}`)"
      - "traefik.http.routers.scrutiny-remote.entrypoints=websecure"
      - "traefik.http.routers.scrutiny-remote.tls.certresolver=cloudflare-remote"
      - "traefik.http.routers.scrutiny-remote.tls.domains[0].main=remote.${DOMAIN_NAME}"
      - "traefik.http.routers.scrutiny-remote.tls.domains[0].sans=*.remote.${DOMAIN_NAME}"

      - "traefik.http.services.scrutiny.loadbalancer.server.port=8080"


volumes:
  scrutiny_config:
  scrutiny_influxdb: