services:

  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - ${SCRUTINY_PORT}:8080
    volumes:
      - /run/udev:/run/udev:ro
      - scrutiny_config:/opt/scrutiny/config
      - scrutiny_influxdb:/opt/scrutiny/influxdb
    devices:
      # Add more devices if you have more than 2 hard drives
      - ${SCRUTINY_DEVICE_01}
      - ${SCRUTINY_DEVICE_02}
    environment:
      - TZ=${TZ}
      - "COLLECTOR_CRON_SCHEDULE=30 4 * * *"

volumes:
  scrutiny_config:
  scrutiny_influxdb: