services:

  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${UPTIME_KUMA_DATA}:/app/data
    environment:
      - PORT=${UPTIME_KUMA_PORT}
