services:

  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ${VAULTWARDEN_DATA}:/data
    ports:
      - ${VAULTWARDEN_PORT}:80
    environment:
      - SIGNUPS_ALLOWED=false # Comment this line to allow signups
