services:

  beszel:
    image: henrygd/beszel:0.12.3
    container_name: homelab-beszel
    restart: unless-stopped
    volumes:
      - beszel-data:/beszel_data
      - beszel-socket:/beszel_socket
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`beszel.${DOMAIN_NAME}`)"
      - "traefik.http.routers.beszel.entrypoints=websecure"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"

  beszel-agent:
    image: henrygd/beszel-agent-nvidia:0.12.3 # Use henrygd/beszel-agent for CPU only
    container_name: homelab-beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - beszel-agent-data:/var/lib/beszel-agent
      - beszel-socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: ${BESZEL_AGENT_KEY}
      TOKEN: ${BESZEL_AGENT_TOKEN}
      HUB_URL: https://beszel.${DOMAIN_NAME}
    # Optional: NVIDIA GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - utility

volumes:
  beszel-data:
    name: homelab-beszel-data
  beszel-socket:
    name: homelab-beszel-socket
  beszel-agent-data:
    name: homelab-beszel-agent-data