services:

  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.17.2-tensorrt
    container_name: homelab-frigate
    restart: unless-stopped
    shm_size: "512mb" # update for your cameras based on calculation above
    stop_grace_period: 30s # allow enough time to shut down the various services
    devices:
      - /dev/bus/usb:/dev/bus/usb # USB passthrough
      - /dev/video0:/dev/video0
      - /dev/video2:/dev/video2
      # Optional: enable NVIDIA GPU acceleration for object detection
      # - nvidia.com/gpu=all 
    volumes:
      - /etc/localtime:/etc/localtime:ro,z
      - ./config.yml:/config/config.yml:ro,z
      - ${FAST_TEMP_STORAGE}/frigate/data:/media/frigate:rw,Z
      - ${FAST_TEMP_STORAGE}/frigate/model-cache:/config/model_cache:rw,Z
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frigate.rule=Host(`frigate.${DOMAIN_NAME}`)"
      - "traefik.http.routers.frigate.entrypoints=websecure"
      - "traefik.http.services.frigate.loadbalancer.server.port=8971"
