services:

  icloud-photo:
    image: icloudpd/icloudpd:1.32.2
    container_name: homelab-icloud-photo
    restart: unless-stopped
    volumes:
      - ${MASS_BACKUP_STORAGE}/data/icloud-photo:/data
    environment:
      - TZ=${TZ}
    command: >-
      icloudpd
      --directory /data
      --username ${ICLOUD_USERNAME}
      --password-provider webui
      --mfa-provider webui
      --watch-with-interval 3600
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.icloud-photo.rule=Host(`icloud-photo.${DOMAIN_NAME}`)"
      - "traefik.http.routers.icloud-photo.entrypoints=websecure"
      - "traefik.http.services.icloud-photo.loadbalancer.server.port=8080"
