services:

  icloud-photo:
    image: icloudpd/icloudpd:latest
    restart: unless-stopped
    volumes:
      - ${ICLOUD_PHOTO_DATA}:/data
    environment:
      - TZ=${TZ}
    command: >-
      icloudpd
      --directory /data
      --username ${ICLOUD_USERNAME}
      --password-provider webui
      --mfa-provider webui
      --watch-with-interval 3600
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.icloud-photo.rule=Host(`icloud-photo.${DOMAIN_NAME}`)"
      - "traefik.http.routers.icloud-photo.entrypoints=websecure"
      - "traefik.http.routers.icloud-photo.tls.certresolver=cloudflare"
      - "traefik.http.routers.icloud-photo.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.icloud-photo.tls.domains[0].sans=*.${DOMAIN_NAME}"

      - "traefik.http.services.icloud-photo.loadbalancer.server.port=8080"
