services:

  oneonefive:
    image: xiuxiu10201/115:latest
    container_name: homelab-oneonefive
    restart: unless-stopped
    volumes:
      - ${FAST_TEMP_STORAGE}/oneonefive:/etc/115
      - ${MASS_TEMP_STORAGE}/oneonefive:/opt/Downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.oneonefive.rule=Host(`oneonefive.${DOMAIN_NAME}`)
      - traefik.http.routers.oneonefive.entrypoints=websecure
      - traefik.http.routers.oneonefive.service=oneonefive
      - traefik.http.services.oneonefive.loadbalancer.server.port=1150