services:

  netdata:
    image: netdata/netdata:v2.7.2
    container_name: homelab-netdata
    restart: unless-stopped
    pid: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${FAST_TEMP_STORAGE}/netdata/config:/etc/netdata
      - ${FAST_TEMP_STORAGE}/netdata/lib:/var/lib/netdata
      - ${FAST_TEMP_STORAGE}/netdata/cache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DISABLE_TELEMETRY=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netdata.rule=Host(`netdata.${DOMAIN_NAME}`)"
      - "traefik.http.routers.netdata.entrypoints=websecure"
      - "traefik.http.services.netdata.loadbalancer.server.port=19999"