services:

  it-tools:
    image: corentinth/it-tools:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.it-tools.rule=Host(`it-tools.${DOMAIN_NAME}`)"
      - "traefik.http.routers.it-tools.entrypoints=websecure"
      - "traefik.http.routers.it-tools.tls.certresolver=cloudflare"
      - "traefik.http.routers.it-tools.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.it-tools.tls.domains[0].sans=*.${DOMAIN_NAME}"

      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
