services:

  glance:
    container_name: homelab-glance
    image: docker.io/glanceapp/glance:v0.8.5
    restart: unless-stopped
    # For mounting the Podman socket
    security_opt:
      [label=disable]
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ${CURRENT_DIR}/podman/glance/glance.yml:/app/config/glance.yml:ro,Z
      - /run/user/${PUID}/podman/podman.sock:/var/run/docker.sock:ro,z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glance.rule=Host(`glance.${DOMAIN_NAME}`)"
      - "traefik.http.routers.glance.entrypoints=websecure"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"
