services:

  grafana:
    image: docker.io/grafana/grafana:13.1.3
    container_name: homelab-grafana
    restart: unless-stopped
    userns_mode: "keep-id:uid=472"
    depends_on:
      - prometheus
    volumes:
      - ${CURRENT_DIR}/podman/grafana/provisioning:/etc/grafana/provisioning:ro,Z
      - ${FAST_TEMP_STORAGE}/grafana:/var/lib/grafana:rw,Z
    environment:
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN_NAME}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  prometheus:
    image: docker.io/prom/prometheus:v3.13.2
    container_name: homelab-prometheus
    restart: unless-stopped
    userns_mode: "keep-id:uid=65534"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${CURRENT_DIR}/podman/grafana/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
      - ${FAST_TEMP_STORAGE}/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN_NAME}`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  node-exporter:
    image: docker.io/prom/node-exporter:v1.12.1
    container_name: homelab-node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,z'
    command:
      - '--path.rootfs=/host'

  telegraf:
    image: docker.io/library/telegraf:1.39.3
    container_name: homelab-telegraf
    restart: unless-stopped
    # For mounting the Podman socket
    security_opt:
      [label=disable]
    userns_mode: "keep-id"
    volumes:
      - ${CURRENT_DIR}/podman/grafana/telegraf.conf:/etc/telegraf/telegraf.conf:ro,Z
      - /run/user/${PUID}/podman/podman.sock:/var/run/docker.sock:ro,z
