[[inputs.docker]]
  gather_services = false
  container_state_include = ["running"]
  perdevice_include = ["cpu", "network", "blkio"]
  total_include = ["cpu"]
  docker_label_include = []
  timeout = "5s"

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
  string_as_label = true
