services:

  komodo-ferretdb:
    image: ghcr.io/ferretdb/ferretdb:1
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: local
    volumes:
      - komodo-sqlite-data:/state
    environment:
      - FERRETDB_HANDLER=sqlite
  
  komodo-core:
    image: ghcr.io/moghtech/komodo-core:latest
    # labels:
    #   komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    depends_on:
      - komodo-ferretdb
    logging:
      driver: local
    environment:
      KOMODO_DATABASE_ADDRESS: komodo-ferretdb
      KOMODO_FIRST_SERVER: https://komodo-periphery:8120
      KOMODO_LOCAL_AUTH: "true"
    volumes:
      - komodo-repo-cache:/repo-cache
    labels:
      - "komodo.skip" # Prevent Komodo from stopping with StopAllContainers

      - "traefik.enable=true"

      - "traefik.http.routers.komodo.rule=Host(`komodo.${DOMAIN_NAME}`)"
      - "traefik.http.routers.komodo.entrypoints=websecure"
      - "traefik.http.routers.komodo.tls.certresolver=cloudflare"
      - "traefik.http.routers.komodo.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.komodo.tls.domains[0].sans=*.${DOMAIN_NAME}"

      - "traefik.http.services.komodo.loadbalancer.server.port=9120"


  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:latest
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    logging:
      driver: local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo

volumes:
  komodo-sqlite-data:
  komodo-repo-cache: