services:

  traefik:
    image: traefik:v3.5.3
    container_name: homelab-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CF_API_TOKEN}
      - CLOUDFLARE_ZONE_API_TOKEN=${CF_API_TOKEN}
      - CLOUDFLARE_POLLING_INTERVAL=10
      - CLOUDFLARE_PROPAGATION_TIMEOUT=300
    command:
      # Docker provider
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Certificate resolvers using Cloudflare DNS challenge
      # - --certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cloudflare.acme.email=${EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.propagation.delayBeforeChecks=10s
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      # HTTP
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      # HTTPS
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN_NAME}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN_NAME}
      # Dashboard
      - --api=true
      # Logging
      - --log.level=INFO
      - --accesslog=true
      # Skip TLS verification
      - --serversTransport.insecureSkipVerify=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${FAST_TEMP_STORAGE}/traefik/letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      # Truenas Scale
      - "traefik.http.routers.truenas.rule=Host(`truenas.${DOMAIN_NAME}`)"
      - "traefik.http.routers.truenas.entrypoints=websecure"
      - "traefik.http.services.truenas.loadbalancer.server.url=https://${TRUENAS_IP}"