services:

  arcane:
    image: ghcr.io/getarcaneapp/manager:v2.9.0
    container_name: homelab-arcane
    restart: unless-stopped
    cgroup: host
    volumes:
      - ${FAST_TEMP_STORAGE}/arcane:/app/data:rw,Z
      - /run/user/${PUID}/docker.sock:/var/run/docker.sock:ro,z
    environment:
      - APP_URL=http://arcane.${DOMAIN_NAME}
      - PUID=0
      - PGID=0
      - ENCRYPTION_KEY=${ARCANE_ENCRYPTION_KEY}
      - JWT_SECRET=${ARCANE_JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arcane.rule=Host(`arcane.${DOMAIN_NAME}`)"
      - "traefik.http.routers.arcane.entrypoints=websecure"
      - "traefik.http.services.arcane.loadbalancer.server.port=3552"
